import { Template } from 'meteor/templating';
import {ReactiveDict} from 'meteor/reactive-dict';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/js/bootstrap';
import '../startup/routes.js';
import './main.html';
import './login.html';
import './login.js';
import './header.html';
import './header.js';
import './home.html';
import './home.js';
import './footer.html';